# Generated by Django 4.2.3 on 2023-07-06 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_remove_prerequisitestype_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='userprofile',
        ),
        migrations.AddField(
            model_name='record',
            name='patient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='record_patient', to='healthcare.userprofile'),
            preserve_default=False,
        ),
    ]
