# Generated by Django 4.2.3 on 2023-07-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prerequisitestype',
            name='package',
        ),
        migrations.AddField(
            model_name='prerequisitestype',
            name='packages',
            field=models.ManyToManyField(to='healthcare.package'),
        ),
    ]
